[hotkeys]
scroll-mode = "cmd-shift-i"
apply-scene = "alt-ctrl-{n}"
hint-mode = "alt-cmd-shift-/"
hint-mode-right-click = "alt-cmd-shift-space"
hint-mode-copy-link = "cmd-shift-l"
text-select = "cmd-shift-y"

[gaps]
outer = 50.0
inner = 50.0

[ignore]
apps = ["Raycast", "Spotlight", "Alfred", "1Password"]

[profile.laptop]
screen-width-max = 3439

[profile.laptop.spaces.1]
apps = ["Ghostty"]

[profile.laptop.spaces.2]
apps = ["Google Chrome"]

[profile.laptop.spaces.3]
apps = ["Slack"]

[profile.laptop.spaces.4]
apps = ["Microsoft Teams"]
hide-windows = ["Calendar"]

[profile.laptop.gaps]
outer = 0
inner = 0

[profile.ultrawide]
screen-width-min = 3440

[profile.ultrawide.spaces.1]
apps = ["Ghostty", "Google Chrome"]

[profile.ultrawide.scene.coding]
number = 1

[profile.ultrawide.scene.coding.spaces.1]
apps = ["Ghostty", "Slack"]

[profile.ultrawide.scene.chat]
number = 2

[profile.ultrawide.scene.chat.spaces.1]
apps = ["Google Chrome", "Microsoft Teams", "Ghostty"]
weights = { "Microsoft Teams" = 2.0 }
hide-windows = ["Calendar"]

