#define FLOW_TAP_TERM 100
#undef TAPPING_TERM
#define TAPPING_TERM 280

#define RETRO_TAPPING

#define USB_SUSPEND_WAKEUP_DELAY 0
#define HOLD_ON_OTHER_KEY_PRESS
#define SERIAL_NUMBER "rAAG9/rbXPMb"
#define LAYER_STATE_16BIT

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

