vim.keymap.set("x", "<Leader>-cs", ":Snek<CR>", { noremap = true, silent = true })
vim.keymap.set("x", "<Leader>-cb", ":Camel<CR>", { noremap = true, silent = true })
vim.keymap.set("x", "<Leader>-cc", ":CamelB<CR>", { noremap = true, silent = true })
vim.keymap.set("x", "<Leader>-ck", ":Kebab<CR>", { noremap = true, silent = true })
vim.keymap.set("x", "<Leader>-cu", ":Screm<CR>", { noremap = true, silent = true })
