set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB"
set -g focus-events on
set -s set-clipboard on
set -s escape-time 0
set -g history-limit 50000
set -g mouse on
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
setw -g mode-keys vi
set -g remain-on-exit off

set-option -g default-shell "/opt/homebrew/bin/fish"
set-option -g default-command "exec /opt/homebrew/bin/fish"

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
bind-key -n 'C-\' if-shell "$is_vim" 'send-keys C-\\' 'select-pane -l'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

bind-key x kill-pane
bind-key '|' split-window -h -c "#{pane_current_path}"
bind-key '-' split-window -v -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"
bind-key r source-file ~/.tmux.conf \; display-message "config reloaded"

bind-key C command-prompt -p "Change directory:" "run-shell '~/.tmux-cd.sh %1'"

bind-key W {
    if-shell -F '#{==:#{session_name},wiki}' {
        detach-client
    } {
        display-popup -E -w 90% -h 85% 'tmux new-session -A -s wiki "tmux set-option status off; exec nvim ~/vimwiki/index.wiki"'
    }
}

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @rose_pine_variant 'main'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option 'default'
set -g @rose_pine_directory 'on'
set -g @rose_pine_date_time '%H:%M'
set -g @rose_pine_default_window_behavior 'on'
set -g @rose_pine_show_current_program 'on'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
