name: Build Corne firmware

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'keyboard/config/**'
      - 'keyboard/build.yaml'
      - '.github/workflows/build-corne.yml'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
    with:
      config_path: keyboard/config
      build_matrix_path: keyboard/build.yaml
